name: Test React App
on: 
  pull_request:
    types: [opened, reopened, edited, closed]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Aplication
        env:
          GITHUB_PULL_TITLE: ${{ github.event.pull_request.title }}
        run: node lint-pull-request.js