name: Test React App
on: 
  push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: install
        run: npm i
      - name: Aplication
        run: node checkBranckName.js
      - name: Test
        run: npm run test