name: Test React App
on: 
  push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: install
        run: npm i
      - name: Aplication
        env:
          PULL_TITLE: ${{ toJson(github.event.pull_request.title) }}
        run: node lint-pull-request.js